Repository ConsenSys/tessera, pull requests merged in 2018-10, with the labels that each got.

#479 Feature/manual add peer
  config-cli/pom.xml
  config-cli/src/main/java/com/quorum/tessera/config/cli/AdminCliAdapter.java
  config-cli/src/main/java/com/quorum/tessera/config/cli/CliAdapter.java
  config-cli/src/main/java/com/quorum/tessera/config/cli/CliDelegate.java
  config-cli/src/main/java/com/quorum/tessera/config/cli/CliResult.java
  config-cli/src/main/java/com/quorum/tessera/config/cli/DefaultCliAdapter.java
  config-cli/src/main/java/com/quorum/tessera/config/cli/parsers/ConfigurationParser.java
  config-cli/src/test/java/com/quorum/tessera/config/cli/AdminCliAdapterTest.java
  config-cli/src/test/java/com/quorum/tessera/config/cli/CliAdapterTest.java
  config-cli/src/test/java/com/quorum/tessera/config/cli/CliDelegateTest.java
  config-cli/src/test/java/com/quorum/tessera/config/cli/DefaultCliAdapterTest.java
  config-migration/src/main/java/com/quorum/tessera/config/migration/LegacyCliAdapter.java
  config/src/main/java/com/quorum/tessera/config/Config.java
  config/src/main/java/com/quorum/tessera/config/util/ConfigFileStore.java
  config/src/main/java/com/quorum/tessera/config/util/ConsolePasswordReader.java
  config/src/test/java/com/quorum/tessera/config/ConfigTest.java
  config/src/test/java/com/quorum/tessera/config/OpenPojoTest.java
  config/src/test/java/com/quorum/tessera/config/util/ConfigFileStoreTest.java
  config/src/test/resources/sample.json
  jaxrs-client/pom.xml
  jaxrs-client/src/main/java/com/quorum/tessera/jaxrs/client/ClientFactory.java
  jaxrs-client/src/test/java/com/quorum/tessera/jaxrs/client/ClientFactoryTest.java
  jaxrs-service/pom.xml
  jaxrs-service/src/main/java/com/quorum/tessera/api/ConfigResource.java
  jaxrs-service/src/main/java/com/quorum/tessera/api/exception/AutoDiscoveryDisabledExceptionMapper.java
  jaxrs-service/src/main/java/com/quorum/tessera/api/exception/DecodingExceptionMapper.java
  jaxrs-service/src/main/java/com/quorum/tessera/api/exception/DefaultExceptionMapper.java
  jaxrs-service/src/main/java/com/quorum/tessera/api/exception/EntityNotFoundExceptionMapper.java
  jaxrs-service/src/main/java/com/quorum/tessera/api/exception/KeyNotFoundExceptionMapper.java
  jaxrs-service/src/main/java/com/quorum/tessera/api/exception/NotFoundExceptionMapper.java
  jaxrs-service/src/main/java/com/quorum/tessera/api/exception/TransactionNotFoundExceptionMapper.java
  jaxrs-service/src/main/java/com/quorum/tessera/api/exception/WebApplicationExceptionMapper.java
  jaxrs-service/src/main/java/com/quorum/tessera/api/filter/IPWhitelistFilter.java
  jaxrs-service/src/main/java/com/quorum/tessera/client/RestP2pClientFactory.java
  jaxrs-service/src/main/resources/tessera-jaxrs-spring.xml
  jaxrs-service/src/test/java/com/quorum/tessera/api/ConfigResourceTest.java
  jaxrs-service/src/test/java/com/quorum/tessera/api/filter/IPWhitelistFilterTest.java
  pom.xml
  tessera-app/src/main/java/com/quorum/tessera/Launcher.java
  tessera-core/src/main/java/com/quorum/tessera/core/config/ConfigService.java
  tessera-core/src/main/java/com/quorum/tessera/core/config/ConfigServiceImpl.java
  tessera-core/src/main/java/com/quorum/tessera/node/PartyInfoPoller.java
  tessera-core/src/main/java/com/quorum/tessera/node/PartyInfoService.java
  tessera-core/src/main/java/com/quorum/tessera/node/PartyInfoServiceImpl.java
  tessera-core/src/main/resources/tessera-core-spring.xml
  tessera-core/src/test/java/com/quorum/tessera/core/config/ConfigServiceTest.java
  tessera-core/src/test/java/com/quorum/tessera/node/PartyInfoServiceTest.java
  tests/acceptance-test/src/test/java/com/quorum/tessera/test/rest/AdminConfigIT.java
  tests/acceptance-test/src/test/java/com/quorum/tessera/test/rest/RestSuite.java
Labels: review

#482 Update communication model
  jaxrs-service/src/main/java/com/quorum/tessera/api/TransactionResource.java
  tessera-core/src/main/java/com/quorum/tessera/enclave/EnclaveImpl.java
  tessera-core/src/main/java/com/quorum/tessera/enclave/EnclaveMediator.java
  tessera-core/src/main/java/com/quorum/tessera/node/PartyInfoParser.java
  tessera-core/src/main/java/com/quorum/tessera/node/PartyInfoServiceImpl.java
  tessera-core/src/test/java/com/quorum/tessera/enclave/EnclaveImplTest.java
  tessera-core/src/test/java/com/quorum/tessera/node/PartyInfoParserTest.java
  tessera-core/src/test/java/com/quorum/tessera/node/PartyInfoServiceTest.java
Labels: review

#481 Add new key pair type for unsupported config combinations
  config-cli/src/test/java/com/quorum/tessera/config/cli/DefaultCliAdapterTest.java
  config/src/main/java/com/quorum/tessera/config/adapters/KeyConfigurationAdapter.java
  config/src/main/java/com/quorum/tessera/config/adapters/KeyDataAdapter.java
  config/src/main/java/com/quorum/tessera/config/constraints/KeyDataValidator.java
  config/src/main/java/com/quorum/tessera/config/constraints/UnsupportedKeyPairValidator.java
  config/src/main/java/com/quorum/tessera/config/constraints/ValidKeyData.java
  config/src/main/java/com/quorum/tessera/config/constraints/ValidUnsupportedKeyPair.java
  config/src/main/java/com/quorum/tessera/config/keypairs/ConfigKeyPair.java
  config/src/main/java/com/quorum/tessera/config/keypairs/DirectKeyPair.java
  config/src/main/java/com/quorum/tessera/config/keypairs/FilesystemKeyPair.java
  config/src/main/java/com/quorum/tessera/config/keypairs/InlineKeypair.java
  config/src/main/java/com/quorum/tessera/config/keypairs/UnsupportedKeyPair.java
  config/src/main/resources/ValidationMessages.properties
  config/src/test/java/com/quorum/tessera/config/KeyDataConfigTest.java
  config/src/test/java/com/quorum/tessera/config/ValidationTest.java
  config/src/test/java/com/quorum/tessera/config/adapters/KeyDataAdapterTest.java
  config/src/test/java/com/quorum/tessera/config/constraints/KeyDataValidatorTest.java
  config/src/test/java/com/quorum/tessera/config/constraints/UnsupportedKeyPairValidatorTest.java
  config/src/test/java/com/quorum/tessera/config/keypairs/FilesystemKeyPairTest.java
  config/src/test/java/com/quorum/tessera/config/keypairs/UnsupportedKeyPairTest.java
Labels: review

#494 Update project configuration
  .editorconfig
  CODEOWNERS
Labels: 0.7

#505 Update p2p discovery
  checkstyle.xml
  config-cli/src/main/java/com/quorum/tessera/config/cli/AdminCliAdapter.java
  jaxrs-service/src/main/java/com/quorum/tessera/api/ConfigResource.java
  tessera-core/src/main/java/com/quorum/tessera/node/PartyInfoServiceImpl.java
  tessera-core/src/main/java/com/quorum/tessera/node/PartyInfoStore.java
  tessera-core/src/test/java/com/quorum/tessera/node/PartyInfoServiceTest.java
  tessera-core/src/test/java/com/quorum/tessera/node/PartyInfoStoreTest.java
Labels: 0.7, enhancement
