Repository ConsenSys/tessera, pull requests merged in 2019-09, with the labels that each got.

#878 Use latest version of Hashicorp Vault in acceptance tests
  .travis.yml
  tests/acceptance-test/src/test/java/com/quorum/tessera/test/vault/hashicorp/HashicorpStepDefs.java
  tests/acceptance-test/src/test/resources/features/vault/hashicorp.feature
  tests/acceptance-test/src/test/resources/vault/tessera-hashicorp-approle-config.json
  tests/acceptance-test/src/test/resources/vault/tessera-hashicorp-config.json
Labels: 0.11, enhancement, testing

#883 ensure jaxrs Responses are closed
  cli/admin-cli/src/main/java/com/quorum/tessera/admin/cli/subcommands/AddPeerCommand.java
  tessera-jaxrs/sync-jaxrs/src/main/java/com/quorum/tessera/p2p/PartyInfoResource.java
  tessera-jaxrs/sync-jaxrs/src/main/java/com/quorum/tessera/p2p/RestP2pClient.java
  tessera-jaxrs/sync-jaxrs/src/main/java/com/quorum/tessera/p2p/RestPayloadPublisher.java
  tests/acceptance-test/pom.xml
  tests/acceptance-test/src/test/java/com/quorum/tessera/test/rest/StressRestSuite.java
  tests/acceptance-test/src/test/java/com/quorum/tessera/test/rest/StressSendIT.java
Labels: 0.11, bug

#888 Update Jackson version to fix a security vulnerability
  pom.xml
Labels: 0.11, security

#886 Limit maximum allow file descriptors for test
  data-migration/src/test/java/com/quorum/tessera/data/migration/CmdLineExecutorTest.java
Labels: 0.11, testing

#890 Azure Key Vault: Use latest client library version
  .travis.yml
  pom.xml
Labels: 0.11, bug, testing
