Repository ConsenSys/tessera, pull requests merged in 2019-06, with the labels that each got.

#774 Clean up tests from deleting temp files
  cli/config-cli/src/test/java/com/quorum/tessera/config/cli/DefaultCliAdapterTest.java
  config-migration/src/test/java/com/quorum/tessera/config/builder/ConfigBuilderTest.java
  config-migration/src/test/java/com/quorum/tessera/config/builder/KeyDataBuilderTest.java
  config-migration/src/test/java/com/quorum/tessera/config/migration/LegacyCliAdapterTest.java
  config-migration/src/test/java/com/quorum/tessera/config/migration/TomlConfigFactoryTest.java
  config/src/test/java/com/quorum/tessera/config/JaxbConfigFactoryTest.java
  config/src/test/java/com/quorum/tessera/config/constraints/PathValidatorTest.java
  key-generation/src/test/java/com/quorum/tessera/key/generation/FileKeyGeneratorTest.java
  pom.xml
  security/src/test/java/com/quorum/tessera/ssl/context/SSLContextBuilderTest.java
  security/src/test/java/com/quorum/tessera/ssl/util/TlsUtilsTest.java
  tests/acceptance-test/src/test/java/com/quorum/tessera/test/cli/KeyGenIT.java
Labels: 1.0, cleanup

#786 Automate tag creation and artifact deployment
  .travis.yml
Labels: 1.0

#788 Remove the deprecated config classes and update tests
  cli/admin-cli/src/test/resources/sample-config.json
  cli/cli-api/src/test/resources/sample-config.json
  cli/config-cli/src/test/java/com/quorum/tessera/config/cli/DefaultCliAdapterTest.java
  cli/config-cli/src/test/java/com/quorum/tessera/config/cli/OverrideUtilTest.java
  cli/config-cli/src/test/resources/keygen-sample.json
  cli/config-cli/src/test/resources/keytests/passwordsMissing.json
  cli/config-cli/src/test/resources/keytests/passwordsWrong.json
  cli/config-cli/src/test/resources/keytests/pubPrivInlineLocked.json
  cli/config-cli/src/test/resources/keytests/pubPrivInlineUnlocked.json
  cli/config-cli/src/test/resources/keytests/pubPrivPasswordsFile.json
  cli/config-cli/src/test/resources/keytests/pubPrivUsingPathsLocked.json
  cli/config-cli/src/test/resources/keytests/pubPrivUsingPathsUnlocked.json
  cli/config-cli/src/test/resources/keytests/pubPrivUsingPathsUnlocked_missingPrivateKey.json
  cli/config-cli/src/test/resources/keytests/pubPrivUsingPathsUnlocked_missingPublicKey.json
  cli/config-cli/src/test/resources/missing-config.json
  cli/config-cli/src/test/resources/sample-config-invalidpath.json
  cli/config-cli/src/test/resources/sample-config.json
  config-migration/src/main/java/com/quorum/tessera/config/builder/ConfigBuilder.java
  config-migration/src/test/java/com/quorum/tessera/config/builder/ConfigBuilderTest.java
  config-migration/src/test/java/com/quorum/tessera/config/migration/LegacyCliAdapterTest.java
  config-migration/src/test/java/com/quorum/tessera/config/migration/TomlConfigFactoryTest.java
  config-migration/src/test/resources/sample-all-values-urlport-not-present.conf
  config/src/main/java/com/quorum/tessera/config/Config.java
  config/src/main/java/com/quorum/tessera/config/DeprecatedServerConfig.java
  config/src/main/java/com/quorum/tessera/config/JaxbConfigFactory.java
  config/src/main/java/com/quorum/tessera/config/constraints/EitherServerConfigsOrServerValidator.java
  config/src/main/java/com/quorum/tessera/config/constraints/ValidEitherServerConfigsOrServer.java
  config/src/main/java/com/quorum/tessera/config/util/JaxbUtil.java
  config/src/test/java/com/quorum/tessera/config/ConfigTest.java
  config/src/test/java/com/quorum/tessera/config/DeprecatedServerConfigTest.java
  config/src/test/java/com/quorum/tessera/config/ValidationTest.java
  config/src/test/java/com/quorum/tessera/config/constraints/EitherServerConfigsOrServerValidatorTest.java
  config/src/test/resources/keypassupdate/newLockedKeyAddInline.json
  config/src/test/resources/keypassupdate/newLockedKeyAddInlineWithExisting.json
  config/src/test/resources/keypassupdate/newLockedKeyAddToFile.json
  config/src/test/resources/keypassupdate/newLockedKeyNoPasswordsSet.json
  config/src/test/resources/keypassupdate/newLockedKeyWithUnlockedPrevious.json
  config/src/test/resources/keypassupdate/nullKeys.json
  config/src/test/resources/mask-fixture-with-private-key-path.json
  config/src/test/resources/mask-fixture.json
  config/src/test/resources/sample-private-key-file-path.json
  config/src/test/resources/sample-private-keygen.json
  config/src/test/resources/sample.json
  config/src/test/resources/sample_bad.json
  config/src/test/resources/sample_full.json
  jaxrs-service/src/test/java/com/quorum/tessera/jaxrs/JaxrsITConfig.java
  tessera-core/src/test/java/com/quorum/tessera/core/CoreIT.java
  tessera-core/src/test/resources/config-with-relay.json
  tessera-core/src/test/resources/config1.json
  tests/acceptance-test/pom.xml
  tests/acceptance-test/src/test/java/com/quorum/tessera/test/migration/config/ConfigMigrationSteps.java
  tests/acceptance-test/src/test/resources/empty-keys-config.json
  tests/acceptance-test/src/test/resources/empty-keyspath-config.json
  tests/jmeter-test/src/test/resources/config1.json
  tests/jmeter-test/src/test/resources/config2.json
Labels: 1.0, cleanup, enhancement, feature
