Repository ConsenSys/tessera, pull requests merged in 2019-05, with the labels that each got.

#724 Remove excess newlines from migration and GRPC modules
  config-migration/src/main/java/com/quorum/tessera/config/builder/ConfigBuilder.java
  config-migration/src/main/java/com/quorum/tessera/config/builder/JdbcConfigFactory.java
  config-migration/src/main/java/com/quorum/tessera/config/builder/SslTrustModeFactory.java
  config-migration/src/main/java/com/quorum/tessera/config/migration/LegacyCliAdapter.java
  config-migration/src/test/java/com/quorum/tessera/config/builder/ConfigBuilderTest.java
  config-migration/src/test/java/com/quorum/tessera/config/builder/JdbcConfigFactoryTest.java
  config-migration/src/test/java/com/quorum/tessera/config/builder/KeyDataBuilderTest.java
  config-migration/src/test/java/com/quorum/tessera/config/migration/MockSystemAdapter.java
  config-migration/src/test/java/com/quorum/tessera/config/migration/TomlConfigFactoryTest.java
  grpc-service/src/main/java/com/quorum/tessera/client/GrpcClient.java
  grpc-service/src/main/java/com/quorum/tessera/client/GrpcClientImpl.java
  grpc-service/src/main/java/com/quorum/tessera/client/GrpcP2pClient.java
  grpc-service/src/main/java/com/quorum/tessera/client/GrpcP2pClientFactory.java
  grpc-service/src/main/java/com/quorum/tessera/grpc/StreamObserverCallback.java
  grpc-service/src/main/java/com/quorum/tessera/grpc/api/APITransactionGrpcService.java
  grpc-service/src/main/java/com/quorum/tessera/grpc/p2p/Convertor.java
  grpc-service/src/test/java/com/quorum/tessera/client/GrpcClientFactoryTest.java
  grpc-service/src/test/java/com/quorum/tessera/grpc/GrpcAppTest.java
  grpc-service/src/test/java/com/quorum/tessera/grpc/GrpcITConfig.java
  grpc-service/src/test/java/com/quorum/tessera/grpc/StreamObserverTemplateTest.java
  grpc-service/src/test/java/com/quorum/tessera/grpc/api/APITransactionGrpcServiceTest.java
  grpc-service/src/test/java/com/quorum/tessera/grpc/p2p/ConvertorTest.java
  grpc-service/src/test/java/com/quorum/tessera/grpc/p2p/P2PTransactionGrpcServiceTest.java
  grpc-service/src/test/java/com/quorum/tessera/grpc/p2p/PartyInfoGrpcServiceTest.java
  server/grpc-server/src/main/java/com/quorum/tessera/grpc/server/GrpcServerFactory.java
Labels: 0.10, cleanup

#733 Load resource stream over file
  config/pom.xml
  config/src/main/java/com/quorum/tessera/config/ServerConfig.java
  data-migration/src/main/java/com/quorum/tessera/data/migration/CmdLineExecutor.java
  data-migration/src/main/java/com/quorum/tessera/data/migration/H2DataExporter.java
  data-migration/src/main/java/com/quorum/tessera/data/migration/Main.java
  data-migration/src/main/java/com/quorum/tessera/data/migration/SqliteDataExporter.java
  data-migration/src/test/java/com/quorum/tessera/data/migration/MainTest.java
  pom.xml
Labels: 0.10, bug

#763 CVE-2019-12086: Upgrade jackson in response to moderate security warning
  pom.xml
Labels: 1.0, enhancement

#765 Read key password from CLI
  cli/cli-api/src/main/java/com/quorum/tessera/cli/keypassresolver/CliKeyPasswordResolver.java
  cli/cli-api/src/main/java/com/quorum/tessera/cli/keypassresolver/KeyPasswordResolver.java
  cli/cli-api/src/main/resources/META-INF/services/com.quorum.tessera.cli.keypassresolver.KeyPasswordResolver
  cli/cli-api/src/test/java/com/quorum/tessera/cli/keypassresolver/CliKeyPasswordResolverTest.java
  cli/config-cli/src/main/java/com/quorum/tessera/config/cli/DefaultCliAdapter.java
  cli/config-cli/src/test/java/com/quorum/tessera/config/cli/DefaultCliAdapterTest.java
  cli/config-cli/src/test/java/com/quorum/tessera/config/cli/keys/KeyReadingTest.java
  config/src/main/java/com/quorum/tessera/config/adapters/KeyDataAdapter.java
  config/src/main/java/com/quorum/tessera/config/constraints/Base64Validator.java
  config/src/main/java/com/quorum/tessera/config/keypairs/FilesystemKeyPair.java
  config/src/main/java/com/quorum/tessera/config/keypairs/InlineKeypair.java
  config/src/main/resources/ValidationMessages.properties
  config/src/test/java/com/quorum/tessera/config/ValidationTest.java
  config/src/test/java/com/quorum/tessera/config/keypairs/InlineKeypairTest.java
  enclave/enclave-server/src/main/java/com/quorum/tessera/enclave/server/EnclaveCliAdapter.java
  enclave/enclave-server/src/test/java/com/quorum/tessera/enclave/server/EnclaveCliAdapterTest.java
Labels: 1.0, feature

#767 Switch the dependency for Argon2 to one provided by BouncyCastle
  argon2/pom.xml
  argon2/src/main/java/com/quorum/tessera/argon2/Argon2.java
  argon2/src/main/java/com/quorum/tessera/argon2/Argon2Impl.java
  argon2/src/test/java/com/quorum/tessera/argon2/Argon2Test.java
  config/src/main/java/com/quorum/tessera/config/keys/KeyEncryptor.java
  config/src/main/java/com/quorum/tessera/config/keys/KeyEncryptorImpl.java
  pom.xml
Labels: 1.0, enhancement
