Repository ConsenSys/tessera, pull requests merged in 2019-12, with the labels that each got.

#937 Only prompt for key passwords on CLI if the pwd is not already given
  cli/cli-api/build.gradle
  cli/cli-api/src/main/java/com/quorum/tessera/cli/keypassresolver/CliKeyPasswordResolver.java
  cli/cli-api/src/test/java/com/quorum/tessera/cli/keypassresolver/CliKeyPasswordResolverTest.java
Labels: 0.11, bug

#941 Add error message if using password list in config
  cli/cli-api/src/main/java/com/quorum/tessera/cli/parsers/ConfigurationParser.java
  cli/cli-api/src/test/java/com/quorum/tessera/cli/parsers/ConfigurationParserTest.java
  cli/cli-api/src/test/resources/sample-config-password-file-only.json
  cli/cli-api/src/test/resources/sample-config-password-file.json
  cli/config-cli/src/main/java/com/quorum/tessera/config/cli/DefaultCliAdapter.java
  cli/config-cli/src/test/java/com/quorum/tessera/config/cli/DefaultCliAdapterTest.java
  config/src/main/java/com/quorum/tessera/config/KeyConfiguration.java
  shared/src/main/java/com/quorum/tessera/io/FilesDelegate.java
  shared/src/test/java/com/quorum/tessera/io/FilesDelegateTest.java
  tessera-dist/tessera-launcher/src/main/java/com/quorum/tessera/launcher/Main.java
Labels: 0.10.2, cleanup

#943 Gradle publish changes
  argon2/build.gradle
  build.gradle
  cli/admin-cli/build.gradle
  config-migration/build.gradle
  config/build.gradle
  enclave/enclave-jaxrs/build.gradle
  gradle.properties
  tessera-dist/tessera-launcher/build.gradle
  tessera-jaxrs/admin-jaxrs/build.gradle
  tessera-jaxrs/common-jaxrs/build.gradle
  tessera-jaxrs/sync-jaxrs/build.gradle
  tessera-jaxrs/thirdparty-jaxrs/build.gradle
  tessera-sync/build.gradle
  test-utils/mock-jaxrs/build.gradle
  test-utils/mock-websocket-container/build.gradle
Labels: 0.10.2, CI/CD
