Repository ConsenSys/tessera, pull requests merged in 2019-08, with the labels that each got.

#844 Add file-based key generation acceptance tests
  tests/acceptance-test/pom.xml
  tests/acceptance-test/src/test/java/com/quorum/tessera/test/cli/CucumberFileKeyGenerationIT.java
  tests/acceptance-test/src/test/java/com/quorum/tessera/test/cli/KeyGenIT.java
  tests/acceptance-test/src/test/java/com/quorum/tessera/test/cli/keygen/FileKeygenSteps.java
  tests/acceptance-test/src/test/java/com/quorum/tessera/test/cli/keygen/FileKeygenStreamConsumer.java
  tests/acceptance-test/src/test/resources/features/cli/file_keygen.feature
Labels: 0.10.0, testing

#845 Jasypt encryption
  README.md
  config/pom.xml
  config/src/main/java/com/quorum/tessera/config/JdbcConfig.java
  config/src/main/java/com/quorum/tessera/config/util/ConfigSecretReader.java
  config/src/main/java/com/quorum/tessera/config/util/EncryptedStringResolver.java
  config/src/main/java/com/quorum/tessera/config/util/EnvironmentVariables.java
  config/src/test/java/com/quorum/tessera/config/util/ConfigSecretReaderTest.java
  config/src/test/java/com/quorum/tessera/config/util/EncryptedStringResolverTest.java
  config/src/test/resources/key.secret
  pom.xml
  tessera-core/src/main/resources/tessera-core-spring.xml
  tests/acceptance-test/src/test/java/admin/cmd/StartupSteps.java
Labels: 0.10.0, feature, security

#847 Add empty party info response for older nodes to consume
  tessera-jaxrs/sync-jaxrs/src/main/java/com/quorum/tessera/p2p/PartyInfoResource.java
  tessera-jaxrs/sync-jaxrs/src/test/java/com/quorum/tessera/p2p/PartyInfoResourceTest.java
Labels: 0.10.0

#851 Downgrade okhttp to 3.12.3 as required by Azure key vault SDK
  pom.xml
Labels: 0.10.0, security

#849 Disable mvn deploy when merging in to master branch
  .travis.yml
Labels: CI/CD

#856 Update Jackson Databinding dependency to newer version
  pom.xml
Labels: security

#858 Print more useful error msgs to syserr for service provider errors
  tessera-dist/tessera-launcher/src/main/java/com/quorum/tessera/launcher/Main.java
Labels: 0.11, bug

#861 Poll (remote) enclave for local public keys
  tessera-partyinfo/src/main/java/com/quorum/tessera/partyinfo/EnclaveKeySynchroniser.java
  tessera-partyinfo/src/main/java/com/quorum/tessera/partyinfo/PartyInfoServiceFactory.java
  tessera-partyinfo/src/main/java/com/quorum/tessera/partyinfo/PartyInfoServiceFactoryImpl.java
  tessera-partyinfo/src/main/java/com/quorum/tessera/partyinfo/PartyInfoServiceImpl.java
  tessera-partyinfo/src/main/java/com/quorum/tessera/partyinfo/PartyInfoStore.java
  tessera-partyinfo/src/main/resources/tessera-partyinfo-spring.xml
  tessera-partyinfo/src/test/java/com/quorum/tessera/partyinfo/EnclaveKeySynchroniserTest.java
  tessera-partyinfo/src/test/java/com/quorum/tessera/partyinfo/PartyInfoServiceFactoryTest.java
  tessera-partyinfo/src/test/java/com/quorum/tessera/partyinfo/PartyInfoServiceTest.java
  tests/acceptance-test/pom.xml
  tests/acceptance-test/src/test/java/com/quorum/tessera/test/rest/SendWithRemoteEnclaveReconnectIT.java
Labels: 0.11, feature

#866 Add generics to Key Vaults
  key-generation/src/main/java/com/quorum/tessera/key/generation/AzureVaultKeyGenerator.java
  key-generation/src/main/java/com/quorum/tessera/key/generation/DefaultKeyGeneratorFactory.java
  key-generation/src/main/java/com/quorum/tessera/key/generation/HashicorpVaultKeyGenerator.java
  key-vault/azure-key-vault/src/main/java/com/quorum/tessera/key/vault/azure/AzureKeyVaultService.java
  key-vault/azure-key-vault/src/test/java/com/quorum/tessera/key/vault/azure/AzureKeyVaultServiceTest.java
  key-vault/hashicorp-key-vault/src/main/java/com/quorum/tessera/key/vault/hashicorp/HashicorpKeyVaultService.java
  key-vault/hashicorp-key-vault/src/test/java/com/quorum/tessera/key/vault/hashicorp/HashicorpKeyVaultServiceTest.java
  key-vault/key-vault-api/src/main/java/com/quorum/tessera/key/vault/KeyVaultService.java
Labels: 0.11, tech debt

#870 Replace uses of ServiceLoader with the utility method
  argon2/pom.xml
  argon2/src/main/java/com/quorum/tessera/argon2/Argon2.java
  cli/cli-api/src/main/java/com/quorum/tessera/cli/CliDelegate.java
  config/src/main/java/com/quorum/tessera/config/ConfigFactory.java
  config/src/main/java/com/quorum/tessera/config/apps/TesseraAppFactory.java
  config/src/main/java/com/quorum/tessera/config/util/EnvironmentVariableProviderFactory.java
  enclave/enclave-api/src/main/java/com/quorum/tessera/enclave/EnclaveClientFactory.java
  encryption/encryption-api/pom.xml
  encryption/encryption-api/src/main/java/com/quorum/tessera/nacl/NaclFacadeFactory.java
  key-vault/key-vault-api/src/main/java/com/quorum/tessera/key/vault/KeyVaultServiceFactory.java
  security/pom.xml
  security/src/main/java/com/quorum/tessera/ssl/context/ClientSSLContextFactory.java
  security/src/main/java/com/quorum/tessera/ssl/context/ServerSSLContextFactory.java
  security/src/main/resources/META-INF/services/com.quorum.tessera.config.util.EnvironmentVariableProviderFactory
  server/server-api/pom.xml
  server/server-api/src/main/java/com/quorum/tessera/server/TesseraServerFactory.java
  service-locator/service-locator-api/pom.xml
  service-locator/service-locator-api/src/main/java/com/quorum/tessera/service/locator/ServiceLocator.java
  shared/src/main/java/com/quorum/tessera/ServiceLoaderUtil.java
  shared/src/test/java/com/quorum/tessera/ServiceLoaderUtilTest.java
  tessera-partyinfo/src/main/java/com/quorum/tessera/partyinfo/P2pClientFactory.java
  tessera-partyinfo/src/main/java/com/quorum/tessera/partyinfo/PayloadPublisherFactory.java
Labels: 0.11, tech debt
