Repository ConsenSys/tessera, pull requests merged in 2020-02, with the labels that each got.

#988 Update Java version requirements in README
  README.md
Labels: 0.10.3, cleanup

#990 Remove leftover GRPC references
  pom.xml
Labels: 0.10.3, cleanup

#991 Update the JNR Unixsocket library
  pom.xml
  server/jaxrs-client-unixsocket/src/test/java/com/quorum/tessera/jaxrs/unixsocket/JerseyServerIT.java
  server/jaxrs-client-unixsocket/src/test/java/com/quorum/tessera/jaxrs/unixsocket/SampleResource.java
  tests/acceptance-test/build.gradle
Labels: 0.10.3, upgrade

#992 Bugfix/whitelist filter
  pom.xml
  tessera-jaxrs/common-jaxrs/src/main/java/com/quorum/tessera/api/filter/IPWhitelistFilter.java
  tessera-jaxrs/common-jaxrs/src/test/java/com/quorum/tessera/api/filter/IPWhitelistFilterTest.java
  tessera-jaxrs/transaction-jaxrs/src/main/java/com/quorum/tessera/q2t/Q2TRestApp.java
  tessera-jaxrs/transaction-jaxrs/src/test/java/com/quorum/tessera/q2t/Q2TRestAppTest.java
  tests/acceptance-test/src/test/java/transaction/whitelist/WhitelistSteps.java
Labels: 0.10.3, bug
