Repository ConsenSys/tessera, pull requests merged in 2021-05, with the labels that each got.

#1286 Upgrade hiberante validator due to CVE-2020-10693 advisory
  .github/workflows/gradle.yml
  build.gradle
Labels: 21.4.1, security

#1287 Check dependencies before release
  .github/workflows/release.yml
Labels: 21.4.1, CI/CD, dependencies

#1285 Include Tessera simple jar and key vault jar dists in the release with gradle build
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  key-vault/aws-key-vault/build.gradle
  key-vault/azure-key-vault/build.gradle
  key-vault/hashicorp-key-vault/build.gradle
  migration/orion-to-tessera/build.gradle
  settings.gradle
  tessera-dist/tessera-simple/build.gradle
  version.txt
Labels: 21.4.1, Release
